### ISSUE TITLE
Sprint #3 review

### ISSUE THREAD

**Issue by lani0016** [https-github-com-beanz/web-app-recycling#41]
finished leftover work for sprint 2, added all boilerplate information and background files, icons were imported and all that remains is making the patterns

**Comment by lani0016** [comment]
I added boilerplate information, created the necessary folders and put in the background files like error 404 page, humans and robots text and started the layouts

**Comment by migr0001** [comment]
Added top navigation for our recycling app.

**Comment by lani0016** [comment]
@thomasjbradley here is our sprint # 3 review!

**Comment by thomasjbradley** [comment]
👍

**Comment by GabbyCinco** [comment]
Added the logo and icon files
